### PR TITLE
Add multiple account support

### PR DESCRIPTION
**Pull request by telotortium**
The myuhe version of org-gcal.el doesn't allow calendars from multiple Google accounts to be synced in the same instance of Emacs, since only a single Google Calendar token can be held. @ayyjayess and @sattisvar have created patches to org-gcal.el that add such support, by turning `org-gcal-token-plist` into `org-gcal-tokens-plist`. I've been using this in my own repo for over half a year at this point and everything has worked seamlessly - I can sync my personal and work accounts into the same Emacs (in separate `gcal.org` files). I've merged these patches into the current `master` version of your repo, so they should be good to go.

### CODE REVIEW

**Comment by kidd** [comment]
Hey!
That's great indeed! I had thought of wrapping mine into `lets` to do the multi-account trick, but if the mode can support it natively, even better.

I've tested it myself and seems to work great :)

Before merging it, I have a few questions though:

1) Does it handle `org-gcal-post-at-point` and `org-gcal-delete-at-point`? I see code to make it work but there are questions on the other repo regarding that, so just to know it (not a user of that feature)

2) There are some (message ....) here and there, are you ok with me cleaning it afterwards, or you prefer to clean that up yourself?

**Comment by bobberb** [comment]
+1 thank you @telotortium  for merging against @kidd !

**Comment by telotortium** [comment]
Hi @kidd:

1. I don't know, I don't use that functionality either.
2. You can clean it up afterwards.

**Comment by kidd** [comment]
So I tried it and *-at-point do not work properly. I'll take this branch from here and try to fix it.

For now it doesn't go into master yet :(.

**Comment by telotortium** [comment]
Yeah, it looks like there's no property containing the calendar ID of the calendar the event came from. One should probably be added. In the meantime, you can infer it from the gcal.org file where the event entry is found using `org-gcal-file-alist`.

**Comment by gciolli** [comment]
FYI I have just posted a fix to a similar problem in the parent repository:

https://github.com/myuhe/org-gcal.el/pull/85

it supports multiple calendars, albeit from a single account (and a single token).
It's not really a restriction as one calendar can access others if they have appropriate sharing configuration.

**Comment by kidd** [comment]
@gciolli, I think I like your fix better than having multiple tokens. also, multiple tokens made it slower as there's one token per calendar, not just per "owner".

When I have some time I'll merge your branch in, and we'll close this one. 

Thanks everyone for your collaboration!

**Comment by kidd** [comment]
I ended up merging #9 which solves the {delete,post}-at-point in a clean way. 

The multiple accounts is a non-issue as one can give calendar permissions to another account via google calendar interface. I think it keeps the code nicer and it's faster.

Thanks all for bringing ideas and PRs.

**Pull request closed without merging**
