### PR TITLE
Fix org-gcal--capture-post

### PR DESCRIPTION
**Pull request by telotortium**
This will also create events when refiling into a file in `org-gcal-fetch-file-alist`.

### CODE REVIEW

**Comment by jlaznarte** [comment]
Hi,

I've tried this functionality and I'm still unable to get a new event automatically synced with google calendar. What I expected is that after capturing an appointment it'd got automatically copied to google calendar, releasing the user from the need to manually run org-gcal-post-at-point.

Have I misunderstood the patch? How can I get that functionality?

Regards,

**Comment by agenbite** [comment]
Hi,

I've tried this functionality and I'm still unable to get a new event automatically synced with google calendar. What I expected is that after capturing an appointment it'd got automatically copied to google calendar, releasing the user from the need to manually run org-gcal-post-at-point.

Have I misunderstood the patch? How can I get that functionality?

Regards,

**Comment by telotortium** [comment]
This patch posts the event if you capture or refile into a file in
org-gcal-fetch-file-alist. I didn't make the hook post absolutely every
captured note, because you may not want to schedule or set a calendar ID
for every single thing - I generally don't schedule events until I know a
time I will work on them.

The easiest way to get what you want is to add a template to
org-capture-templates that captures into an gcal file. If that's not what
you want, there are other hooks you could write that are similar to the
hooks added in this PR, but I don't know if I'd want to maintain those in
the main org-gcal codebase.

**Comment by agenbite** [comment]
Thanks for your help. I agree with your vision, there's no need to post everything.

What is the difference between org-gcal-file-alist (as documented in the README) and org-gcal-fetch-file-alist?

I do have a template that captures into a gcal file:

`("a" "Appointment" entry (file "~/org/gcalendar.org")
              "* %?\n:PROPERTIES:\n:calendar-id:\tmy-google-id@gmail.com\n:END:\n:org-gcal:\n%^T\n:END:\n\n" :jump-to-captured t)`

After capturing, the event is copied to the file allright, but it stops there: no post-at-point. Also, after running org-gcal-sync, any new events created with the template do not get copied into my google calendar either.

 Am I doing something wrong?

Thanks again for this fine piece of software.

**Comment by HanshenWang** [comment]
@agenbite 

If you're still working it out, I have found https://github.com/kidd/org-gcal.el/issues/62 to be of much help. Indeed, I intuitively first tried "org-capture-prepare-finalize-hook" combined with "evil-goto-first-line" and "org-gcal-post-at-point". It worked calling the function manually in the buffer, but I ran into the same issues as the link above when calling from a hook. Telotortium gave an excellent pointer,

"You may be able to run it from org-capture-after-finalize-hook, if you run org-capture-goto-last-stored in order to place the point at the location of the captured event."

For completeness sake, here is my capture template,

```
                          ("a" "Set Appointment" entry (file  "~/Dropbox/project-maria/task-management/0inbox.org" )
                           "* %?
            :PROPERTIES:
            :LOCATION: %^{LOCATION|TBD}
            :calendar-id: %^{calendar-id|youremail@gmail.com}
            :EFFORT: %^{0:00|0:10|0:30|1:00|1:30|2:00|2:30|3:00|4:00|5:00|6:00|7:00|8:00}
            :ASSIGNED: %U
            :END:
            :org-gcal:
            %^T
            :END:")
```
and the hook,
```
            (defun hanshen/org-post-appt-to-gcal ()
              "Post capture hook for appointments that post event to Google Calendar"
              (if (equal (plist-get org-capture-plist :key) "a")
                  (progn (org-capture-goto-last-stored) (org-gcal-post-at-point))))
            (add-hook 'org-capture-after-finalize-hook 'hanshen/org-post-appt-to-gcal)
```
Everything works as expected. Emacs 27.1 w/ Spacemacs

Hope that helps!

**Comment by agenbite** [comment]
It does help!! :) Thanks, it works like a charm now.

**Pull request merged**
