### PR TITLE
Re-bind special variables in callbacks executed by request

### PR DESCRIPTION
**Pull request by telotortium**
In order for overriding special and custom variables in a `let` form to work
correctly, the values of the relevant variables must be re-bound inside the
callbacks executed by `request`.

### CODE REVIEW

**Comment by kidd** [comment]
Hi,
What use case does this fulfill? Could you explain a bit why we need those localized values?

Thanks!

**Comment by telotortium** [comment]
This isn't strictly supported, but I call org-gcal--post-event directly to post events to a calendar of mine directly without having to create a file. (I use it to create calendar events to notify my of the end of my break  in org-pomodoro - see https://github.com/telotortium/emacs.d/blob/b68232bce64b6c2bc488ed56a0c0f92b01f3f106/init.el#L976 for the actual code). More generally, dynamically-scoped variables don't seem to work correctly in deferred tasks - the [deferred.el README](https://github.com/kiwanami/emacs-deferred/tree/2239671d94b38d92e9b28d4e12fd79814cfb9c16#excursion-current-status) contains an obscure reference to this.

**Comment by kidd** [comment]
Oh I see. The use case is 100% legit, but here's the thing:

I'm experimenting with `oauth2.el` because I'd like to get rid of the manual token management and  `deferred.el` altogether.  If that goes through, that same hack won't be possible anyway.

Let's wait a bit if I get to do it. I'll have that use case in mind so there's a way to post an event to a calendar without relying on global state.

**Comment by telotortium** [comment]
Since there's been some trouble on the oauth2, I've ended up working more on this branch. I've created a macro to save and restore all org-gcal dynamic variables and used it for all deferred callbacks.

**Comment by telotortium** [comment]
Closing now - the code has probably changed too much for this PR as is to remain viable. Also, I'm moving forward with a different OAuth2 implementation in #191.

**Pull request closed without merging**
