### PR TITLE
Fix Readme (Issue #213)

### PR DESCRIPTION
**Pull request by malleyeno**
This PR fixes issue #213 by updating the readme file with the changes made to get around the new Oauth2-auto method being used for authentication. It also has some items from the discussion has in that issue, including:
- snippets for regular syncing
- `org-capture-template` snippet with details on which parts need to be edited
- Context around how users of the old OOB flow will have to migrate before Jan 31, since that's when Google is pulling the plug
- Potential fix steps for an issue with `PLSTORE` and `oauth2-auto.plist` not saving its buffer properly.
- A note on `org-gcal-sync` that the command does not post newly created events up, as that is handled by `org-gcal-post-at-point`.

**Issues**
I noticed while reviewing the change log that git generated that there are over 800 changes in this PR. I believe this may be due to how it got separated into line breaks within paragraphs when I tried to fork from master in Magit, since I know I did not edit the entire readme file (though I don't know if it was like that originally).

If this is an issue preventing merge, I would appreciate support in figuring out how to get just the relevant edits made.

### CODE REVIEW

**Comment by aspiers** [comment]
@malleyeno If I view the diff with the option to ignore whitespace enabled then it looks correct, so you probably just need to remove the changes to the EOL characters or whatever is causing these whitespace differences.

**Comment by telotortium** [comment]
@malleyeno Please fix the diff before I review the changes.

**Comment by malleyeno** [comment]
@telotortium Should be good now! Turns out that it was a CRLF issue. I just switched over to LF.

There were additions to the readme about asymmetrical keys that were reported as conflicts. I kept both in there just in case one ends up working for the user over the other.

**Comment by licht1stein** [comment]
Updating readme is a very good idea :)

**Comment by marcelruland** [comment]
I just set up org-gcal using this readme after I got properly confused by the one on main. This PR should be merged.

**Comment by telotortium** [comment]
@marcelruland merged - sorry for leaving this unmerged.

**Pull request merged**
