### PR TITLE
Fix #172, point to beginning for parsing headline

### LINKED ISSUE #172: rx--translate-bounded-repetition: rx ‘**’ range error
I requested a new token today, and then `org-gcal-fetch` stop working. I am using Doom with `emacs-mac`. Any helps would be much appreciated. The below is copied from Backtrace. 

``` emacs-lisp
Debugger entered--Lisp error: (error "rx ‘**’ range error")
  signal(error ("rx ‘**’ range error"))
  error("rx `%s' range error" **)
  rx--translate-bounded-repetition(** (1 0 "*"))
  rx--translate-**((1 0 "*"))
  rx--translate-form((** 1 0 "*"))
  rx--translate((** 1 0 "*"))
  mapcar(rx--translate (line-start (** 1 0 "*") " "))
  rx--translate-seq((line-start (** 1 0 "*") " "))
  rx--translate-form((seq line-start (** 1 0 "*") " "))
  rx--translate((seq line-start (** 1 0 "*") " "))
  rx-to-string((seq line-start (** 1 0 "*") " "))
  org-element-headline-parser(2525 t)
  org-gcal--archive-old-event()
  org-gcal-sync(t)
  org-gcal-fetch()
  funcall-interactively(org-gcal-fetch)
  call-interactively(org-gcal-fetch nil nil)
  command-execute(org-gcal-fetch)
```

### PR DESCRIPTION
**Pull request by rhaps0dy**
To parse an org headline, the point needs to be at the beginning of it.
After that, we move to the timestamp to parse it too.

Fixes #172

### CODE REVIEW

**Comment by rhaps0dy** [comment]
In my setup, all headlines are broken without this fix. I'll come up with a test for `org-gcal--archive-old-event `, for which there is none at the moment.

**Comment by telotortium** [comment]
Thanks, I will look at this in a few hours

**Comment by rhaps0dy** [comment]
Finally added the test! I've used some macros from `org-test`, which is used to test Org mode code. The code to find it is on the `(require)` form at the top of the test file. I've tried to make finding `org-test.el` work for other people, but I can't be fully sure.

I've also fixed another "bug", which only came up if your `org-archive-location` is in the same file: the same entries would be "archived" over and over because they would be found by the loop many times. Also entries that are not calendar items were archived as well. That is now fixed and the test tests for it.

**Comment by John-Goff** [comment]
I tested this branch, can confirm it fixes #172 for my setup. Thanks!

**Comment by maikol-solis** [comment]
Another happy user here. All my old events are archived properly with this PR. Thanks!

**Comment by telotortium** [comment]
Thanks - I'd love to merge this, but the code to find `org-test` doesn't seem to work on the Github Actions CI for some reason:

```
Cannot open load file: No such file or directory, /nix/store/114zrlnbkbqfvlsm0sialj7fyva305sv-emacs-27.1/share/emacs/27.1/lisp/testing/org-test.el
```

**Comment by telotortium** [comment]
It's because we're trying to load the built-in Emacs `org` rather than downloading it from Melpa. Need to figure out how to download it.

**Comment by telotortium** [comment]
I've debugged following the instructions in https://github.com/marketplace/actions/debugging-with-ssh, and it seems like we're using the built-in Org. We need to download Org from the Org package repository.

**Comment by telotortium** [comment]
I'm still having trouble figuring out how to retrieve the testing files from upstream. It may be best just to manually add `org-test.el` to the repo, since the `testing` directory isn't included by default in Org as installed via ELPA (or builtin to Emacs).

**Comment by telotortium** [comment]
@rhaps0dy I've been adding some additional fixes to the tests in #192. I've finally gotten it to the point where everything works except for org-gcal-test--headline-archive-old-event: https://github.com/kidd/org-gcal.el/runs/5656094259?check_suite_focus=true

**Comment by telotortium** [comment]
I'm going to close this in favor of #192.

**Pull request closed without merging**
